// Client-side shape validation for the public leaderboard snapshot.
//
// The JSON is generated by the evaluation-side publisher but the browser treats
// it as untrusted input. This module validates the expected top-level shape and
// the fields the leaderboard actually needs; malformed optional display fields
// are ignored rather than treated as fatal.

export interface MetricDefinition {
  name: string;
  higher_is_better: boolean;
}

export interface LeaderboardEntry {
  rank: number;
  team_display_name: string;
  metrics: Record<string, number>;
  metric_ranks?: Record<string, number>;
  mean_rank?: number;
  submission_timestamp?: string;
  method_label?: string;
  evaluation_protocol_version?: string;
}

export interface TrackLeaderboard {
  metrics: MetricDefinition[];
  entries: LeaderboardEntry[];
}

export interface LeaderboardSnapshot {
  schema_version: number;
  generated_at: string;
  ranking_policy?: {
    submission_selection?: string;
    method?: string;
  };
  tracks: {
    "track-1": TrackLeaderboard;
    "track-2": TrackLeaderboard;
  };
}

export interface ValidationResult {
  ok: boolean;
  errors: string[];
  warnings: string[];
}

const TRACK_IDS = ["track-1", "track-2"] as const;

function isRecord(value: unknown): value is Record<string, unknown> {
  return typeof value === "object" && value !== null && !Array.isArray(value);
}

function isFiniteNumber(value: unknown): value is number {
  return typeof value === "number" && Number.isFinite(value);
}

/** Parse a metric-definition list; malformed entries are skipped. */
function parseMetricDefinitions(value: unknown): MetricDefinition[] {
  if (!Array.isArray(value)) return [];
  const result: MetricDefinition[] = [];
  for (const item of value) {
    if (!isRecord(item)) continue;
    if (typeof item.name !== "string" || item.name.length === 0) continue;
    if (typeof item.higher_is_better !== "boolean") continue;
    result.push({ name: item.name, higher_is_better: item.higher_is_better });
  }
  return result;
}

/**
 * Validate an untrusted leaderboard document. `errors` are fatal (the board
 * must not render); `warnings` describe ignorable optional-field problems.
 */
export function validateLeaderboard(data: unknown): ValidationResult {
  const errors: string[] = [];
  const warnings: string[] = [];

  if (!isRecord(data)) {
    return { ok: false, errors: ["leaderboard document must be an object"], warnings };
  }

  if (data.schema_version !== 1) {
    errors.push(`unsupported schema_version: ${String(data.schema_version)}`);
  }
  if (typeof data.generated_at !== "string" || data.generated_at.length === 0) {
    errors.push("generated_at must be a non-empty string");
  }

  if (!isRecord(data.tracks)) {
    return { ok: false, errors: [...errors, "tracks must be an object"], warnings };
  }

  const tracks: LeaderboardSnapshot["tracks"] = {} as LeaderboardSnapshot["tracks"];
  for (const trackId of TRACK_IDS) {
    const rawTrack = data.tracks[trackId];
    if (!isRecord(rawTrack)) {
      errors.push(`tracks.${trackId} must be an object`);
      continue;
    }
    const metrics = parseMetricDefinitions(rawTrack.metrics);
    if (!Array.isArray(rawTrack.entries)) {
      errors.push(`tracks.${trackId}.entries must be an array`);
      continue;
    }

    const entries: LeaderboardEntry[] = [];
    for (const rawEntry of rawTrack.entries) {
      if (!isRecord(rawEntry)) {
        warnings.push(`tracks.${trackId} contains a non-object entry (ignored)`);
        continue;
      }
      if (!isFiniteNumber(rawEntry.rank)) {
        warnings.push(`tracks.${trackId} entry has invalid rank (ignored)`);
        continue;
      }
      if (typeof rawEntry.team_display_name !== "string") {
        warnings.push(`tracks.${trackId} entry has invalid team_display_name (ignored)`);
        continue;
      }
      if (!isRecord(rawEntry.metrics)) {
        warnings.push(`tracks.${trackId} entry has invalid metrics (ignored)`);
        continue;
      }
      const entryMetrics: Record<string, number> = {};
      for (const metric of metrics) {
        const value = rawEntry.metrics[metric.name];
        if (isFiniteNumber(value)) {
          entryMetrics[metric.name] = value;
        }
      }

      const entry: LeaderboardEntry = {
        rank: rawEntry.rank as number,
        team_display_name: rawEntry.team_display_name as string,
        metrics: entryMetrics,
      };
      if (isRecord(rawEntry.metric_ranks)) {
        const metricRanks: Record<string, number> = {};
        for (const [key, value] of Object.entries(rawEntry.metric_ranks)) {
          if (isFiniteNumber(value)) metricRanks[key] = value;
        }
        if (Object.keys(metricRanks).length > 0) entry.metric_ranks = metricRanks;
      }
      if (isFiniteNumber(rawEntry.mean_rank)) entry.mean_rank = rawEntry.mean_rank as number;
      if (typeof rawEntry.submission_timestamp === "string") {
        entry.submission_timestamp = rawEntry.submission_timestamp;
      }
      if (typeof rawEntry.method_label === "string") {
        entry.method_label = rawEntry.method_label;
      }
      if (typeof rawEntry.evaluation_protocol_version === "string") {
        entry.evaluation_protocol_version = rawEntry.evaluation_protocol_version;
      }
      entries.push(entry);
    }

    tracks[trackId] = { metrics, entries };
  }

  return {
    ok: errors.length === 0,
    errors,
    warnings,
  };
}

/** Convenience: validate and narrow the type in one step. */
export function parseLeaderboard(data: unknown): {
  snapshot: LeaderboardSnapshot | null;
  result: ValidationResult;
} {
  const result = validateLeaderboard(data);
  if (!result.ok) return { snapshot: null, result };
  return { snapshot: data as LeaderboardSnapshot, result };
}
